site_name: DSP-UI documentation

nav:
    - Introduction: introduction.md
    - User Guide:
        - Getting Started: how-to-use/getting-started.md
        - Action module:
            - Readme: how-to-use/action/index-action.md
            - AdminImage: how-to-use/action/admin-image.md
            - ExistingName: how-to-use/action/existing-name.md
            - Key: how-to-use/action/key.md
            - Message: how-to-use/action/message.md
            - Progress indicator: how-to-use/action/progress-indicator.md
            - SortButton: how-to-use/action/sort-button.md
            - StringifyStringLiteral: how-to-use/action/stringify-string-literal.md
            - Truncate: how-to-use/action/truncate.md
        - Core module:
          - Readme: how-to-use/core/index-core.md
        - Search module:
          - Readme: how-to-use/search/index-search.md
          - Search-panel: how-to-use/search/search-panel.md
          - Fulltext search: how-to-use/search/fulltext-search.md
          - Extended search: how-to-use/search/extended-search.md
          - Expert search: how-to-use/search/expert-search.md
        - Viewer module:
          - Readme: how-to-use/viewer/index-viewer.md
          - Search-results: how-to-use/viewer/search-results.md
    - Contribution:
      - How to contribute: how-to-contribute/contribution.md
      - Design Documentation: how-to-contribute/design-documentation.md
      - Release Notes: how-to-contribute/release-notes.md

plugins:
    - include-markdown

theme:
  name: material
  logo: 'assets/icons/dasch-icon-white.svg'
  favicon: 'assets/icons/dasch-favicon.ico'
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
  features:
    - navigation.tabs
    - navigation.tabs.sticky

extra_css:
  - 'assets/style/theme.css'
